---
name: Scrapy test container
author: Danilo Ješić
version: 1

services:
  scrapy-tests:
    image: python:3.11-slim
    cmd: bash
    setup-commands:
      - cd /tmp/repo/tests/
      - apt update && apt install -y tox
      - python -m pip install -r requirements.txt

flow:
  - name: Run Scrapy tests with tox
    container: scrapy-tests
    commands:
      - type: console
        command: tox
        note: Starting the scrapy tests