---
name: Scrapy test container
author: Danilo Ješić
version: 1

services:
  scrapy-tests:
    image: python:3.11-slim
    cmd: bash
    setup-commands:
      - python -m pip install -r /tmp/repo/tests/requirements.txt
      - apt update && apt install -y tox
      - cp -R /tmp/repo/ ~/scrapy

flow:
  - name: Run Scrapy tests with tox
    container: scrapy-tests
    commands:
      - type: console
        command: tox -c ~/scrapy/tox.ini
        note: Starting the scrapy tests